apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodetestrollback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodetestrollback
  template:
    metadata:
      labels:
        app: nodetestrollback
    spec:
      containers:
      - name: nodeserver
        image: sanjaytarase/nodetestrollback:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodetestrollback
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31111
